---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html
    - /bin/mkdir -p $DEPLOYPATH/admin
    - /bin/cp -R web/landing/dist/* $DEPLOYPATH
    - /bin/cp -R web/admin/dist/* $DEPLOYPATH/admin
