-- Generated by scripts/generate_content_seed.mjs
-- Source: backend/src/seedData.ts and backend/scripts/seed_questions.ts

insert into public.resources (
  title,
  description,
  content,
  content_format,
  image,
  category,
  tag,
  time,
  color,
  status,
  tags,
  access
)
values
(
  'The Art of Mindful Breathing',
  'Learn how to use your breath to calm your nervous system instantly.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '5 min',
  '#E0F2F1',
  'active',
  '["Stress","Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Building Better Morning Habits',
  'Transform your day by implementing these simple morning rituals.',
  '',
  'html',
  '',
  'Self-development',
  'HABIT',
  '8 min',
  '#FFF3E0',
  'active',
  '["Energy","Motivation"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Managing Workplace Stress',
  'Practical tips to keep your cool during high-pressure work days.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '12 min',
  '#E3F2FD',
  'active',
  '["Stress"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Reset Your Nervous System',
  'A short grounding routine to reduce overwhelm in 10 minutes.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '10 min',
  '#E8F5E9',
  'active',
  '["Stress","Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Focus Sprint: 25-Minute Deep Work',
  'Use a simple sprint to improve concentration and finish tasks.',
  '',
  'html',
  '',
  'Self-development',
  'HABIT',
  '7 min',
  '#E0F7FA',
  'active',
  '["Focus","Motivation"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Sleep Wind-Down Checklist',
  'Create an evening routine that makes sleep easier.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '6 min',
  '#F3E5F5',
  'active',
  '["Energy","Stress"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Confidence in Small Talk',
  'Simple prompts to ease social anxiety in new groups.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '9 min',
  '#FCE4EC',
  'active',
  '["Social Connection"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Reclaim Your Afternoon Energy',
  'Avoid the 3pm slump with quick resets.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '5 min',
  '#FFF8E1',
  'active',
  '["Energy","Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Values-Driven Goal Setting',
  'Align weekly goals with what matters most to you.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '11 min',
  '#E3F2FD',
  'active',
  '["Motivation","Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Boundaries That Stick',
  'Scripts for saying no without guilt.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '8 min',
  '#EDE7F6',
  'active',
  '["Stress","Social Connection"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Five-Minute Gratitude Reset',
  'Shift your mood with a short gratitude exercise.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '5 min',
  '#FFF3E0',
  'active',
  '["Motivation","Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'A Better Way to Break Procrastination',
  'Use tiny starts to reduce resistance.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '7 min',
  '#E8F5E9',
  'active',
  '["Focus","Motivation"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Calm Before Difficult Conversations',
  'Preparation steps that reduce stress and improve outcomes.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '9 min',
  '#E0F2F1',
  'active',
  '["Stress","Social Connection"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Evening Stretch for Better Sleep',
  'Light stretches to release tension.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '6 min',
  '#E3F2FD',
  'active',
  '["Energy","Stress"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Group Walk Challenge',
  'Start a weekly circle walk to build consistency.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '20 min',
  '#E8F5E9',
  'active',
  '["Energy","Social Connection"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Peer Accountability Sprint',
  'Co-work for 30 minutes and share progress.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '30 min',
  '#E0F7FA',
  'active',
  '["Focus","Motivation"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Stress-Free Huddle',
  'A guided group check-in to release stress.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '15 min',
  '#F3E5F5',
  'active',
  '["Stress","Social Connection"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Community Gratitude Circle',
  'Share wins to boost motivation together.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '12 min',
  '#FFF8E1',
  'active',
  '["Motivation","Social Connection"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Evening Reflection Circle',
  'Reflect on highs and lows with your circle.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '18 min',
  '#EDE7F6',
  'active',
  '["Focus","Social Connection"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Mindful Breathing Group',
  'A shared 5-minute breathing break.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '5 min',
  '#E0F2F1',
  'active',
  '["Stress"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Goal-Setting Workshop',
  'Set weekly goals and pair up for accountability.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '25 min',
  '#E3F2FD',
  'active',
  '["Motivation","Focus"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Social Recharge Challenge',
  'Reach out to one person each day for a week.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '7 min',
  '#FCE4EC',
  'active',
  '["Social Connection"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Micro-Breaks for Focus',
  'Take 2-minute breaks to reset attention.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '4 min',
  '#E0F7FA',
  'active',
  '["Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Stress-Proof Morning',
  'A morning flow that keeps your nervous system steady.',
  '',
  'html',
  '',
  'Self-development',
  'HABIT',
  '9 min',
  '#E3F2FD',
  'active',
  '["Stress","Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Motivation Reset Ritual',
  'A quick routine to restart momentum.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '6 min',
  '#E8F5E9',
  'active',
  '["Motivation"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Focus Playlist Strategy',
  'Use sound to create a deep work zone.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '5 min',
  '#E0F2F1',
  'active',
  '["Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Calm the Body Fast',
  'Simple techniques to lower physical stress.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '5 min',
  '#F3E5F5',
  'active',
  '["Stress"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Connect With a Friend',
  'Low-effort ideas to rebuild social energy.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '6 min',
  '#FCE4EC',
  'active',
  '["Social Connection"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Energy Through Nutrition',
  'Simple fuel swaps for steadier energy.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '7 min',
  '#FFF8E1',
  'active',
  '["Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Confidence for Hard Tasks',
  'A short checklist to start tough work.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '6 min',
  '#EDE7F6',
  'active',
  '["Motivation","Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Recover After Conflict',
  'Steps to calm down and reconnect.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '8 min',
  '#FCE4EC',
  'active',
  '["Stress","Social Connection"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Weekly Planning Lite',
  'A 10-minute plan to reduce overwhelm.',
  '',
  'html',
  '',
  'Self-development',
  'HABIT',
  '10 min',
  '#E3F2FD',
  'active',
  '["Focus","Stress"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Energy Check-In',
  'A simple self-scan to pace your day.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '4 min',
  '#FFF8E1',
  'active',
  '["Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Social Warm-Up',
  'Easy prompts to start conversations.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '5 min',
  '#FCE4EC',
  'active',
  '["Social Connection"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Stress Relief Walk',
  'A 10-minute walk to decompress.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '10 min',
  '#E8F5E9',
  'active',
  '["Stress","Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Motivation Through Meaning',
  'Reconnect with your core values.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '9 min',
  '#E8F5E9',
  'active',
  '["Motivation"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Focus-Friendly Workspace',
  'Arrange your space for deep work.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '6 min',
  '#E0F7FA',
  'active',
  '["Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Evening Digital Detox',
  'Lower stimulation before sleep.',
  '',
  'html',
  '',
  'Self-development',
  'HABIT',
  '7 min',
  '#F3E5F5',
  'active',
  '["Stress","Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Gratitude Text Challenge',
  'Send one thankful message each day.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '5 min',
  '#FFF8E1',
  'active',
  '["Motivation","Social Connection"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Co-Working Focus Session',
  'Join a 45-minute group focus block.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '45 min',
  '#E0F7FA',
  'active',
  '["Focus","Motivation"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Group Stretch Break',
  'A short stretch routine with your circle.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '8 min',
  '#E8F5E9',
  'active',
  '["Energy","Stress"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Evening Wins Share',
  'Share a small win with the group.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '6 min',
  '#EDE7F6',
  'active',
  '["Motivation","Social Connection"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Morning Intention Circle',
  'Set a daily intention with your team.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '6 min',
  '#E3F2FD',
  'active',
  '["Focus","Motivation"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Stress Check-In Huddle',
  'Rate stress together and share coping ideas.',
  '',
  'html',
  '',
  'Group activities',
  'GROUP',
  '10 min',
  '#F3E5F5',
  'active',
  '["Stress","Social Connection"]'::jsonb,
  '{"kind":"group_activity","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Energy Boost Playlist',
  'A short music break to lift energy.',
  '',
  'html',
  '',
  'Self-development',
  'PRACTICE',
  '4 min',
  '#FFF8E1',
  'active',
  '["Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Focus Anchor Technique',
  'Return attention quickly when distracted.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '5 min',
  '#E0F7FA',
  'active',
  '["Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Motivation From Progress',
  'Track tiny wins to stay consistent.',
  '',
  'html',
  '',
  'Self-development',
  'HABIT',
  '6 min',
  '#E8F5E9',
  'active',
  '["Motivation"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Social Confidence Reframe',
  'Reframe anxious thoughts before events.',
  '',
  'html',
  '',
  'Self-development',
  'LEARN',
  '7 min',
  '#FCE4EC',
  'active',
  '["Social Connection","Stress"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Stress Boundary Scripts',
  'Phrases to protect your time.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '6 min',
  '#EDE7F6',
  'active',
  '["Stress"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Energy-Friendly Lunch',
  'Small meal tweaks that reduce crashes.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '5 min',
  '#FFF8E1',
  'active',
  '["Energy"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Focus With Time Blocks',
  'Plan deep work windows in your day.',
  '',
  'html',
  '',
  'Self-development',
  'HABIT',
  '8 min',
  '#E0F7FA',
  'active',
  '["Focus"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Motivation Through Rewards',
  'Use small rewards to sustain effort.',
  '',
  'html',
  '',
  'Self-development',
  'READ',
  '6 min',
  '#E8F5E9',
  'active',
  '["Motivation"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
),
(
  'Social Connection Micro-Goals',
  'Set tiny goals to stay connected.',
  '',
  'html',
  '',
  'Self-development',
  'HABIT',
  '5 min',
  '#FCE4EC',
  'active',
  '["Social Connection"]'::jsonb,
  '{"kind":"self_development","plans":["pro"],"shareRequiresPremium":false}'::jsonb
)
on conflict (title) do update
set
  description = excluded.description,
  content = excluded.content,
  content_format = excluded.content_format,
  image = excluded.image,
  category = excluded.category,
  tag = excluded.tag,
  time = excluded.time,
  color = excluded.color,
  status = excluded.status,
  tags = excluded.tags,
  access = excluded.access,
  updated_at = timezone('utc', now());

insert into public.challenges (
  title,
  description,
  level,
  icon,
  bg,
  color,
  category,
  priority,
  status,
  tags,
  is_active
)
values
(
  'Work-Life Balance',
  'Maintain a healthy boundary between work and personal life.',
  'Moderate',
  'briefcase-outline',
  '#E3F2FD',
  '#2196F3',
  'Stress',
  10,
  'active',
  '[]'::jsonb,
  true
),
(
  'Social Anxiety',
  'Strategies to manage discomfort in social settings.',
  'High',
  'account-group-outline',
  '#F3E5F5',
  '#8E24AA',
  'Social Connection',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Public Speaking',
  'Build confidence in presenting to groups.',
  'Moderate',
  'bullhorn-outline',
  '#E1F5FE',
  '#0288D1',
  'Social Connection',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Procrastination',
  'Overcome the tendency to delay important tasks.',
  'Moderate',
  'clock-outline',
  '#FFF3E0',
  '#FF9800',
  'Focus',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Sleep Hygiene',
  'Improve your sleep quality with better routines.',
  'Low',
  'bed-outline',
  '#E8F5E9',
  '#4CAF50',
  'Energy',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Overthinking Spiral',
  'Reduce rumination with quick grounding techniques.',
  'High',
  'thought-bubble-outline',
  '#F3E5F5',
  '#8E24AA',
  'Stress',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Afternoon Slump',
  'Boost energy with short breaks and hydration.',
  'Low',
  'weather-sunset-up',
  '#FFF8E1',
  '#F9A825',
  'Energy',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Low Motivation Week',
  'Rebuild momentum with tiny wins and clear goals.',
  'Moderate',
  'flag-outline',
  '#E8F5E9',
  '#43A047',
  'Motivation',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Social Disconnection',
  'Reconnect with people through low-pressure outreach.',
  'High',
  'account-question-outline',
  '#FCE4EC',
  '#D81B60',
  'Social Connection',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Focus Drift',
  'Improve concentration with timed sprints.',
  'Moderate',
  'target-variant',
  '#E0F7FA',
  '#00838F',
  'Focus',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Decision Fatigue',
  'Simplify choices to preserve mental energy.',
  'Moderate',
  'playlist-check',
  '#EDE7F6',
  '#5E35B1',
  'Focus',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Conflict Recovery',
  'Repair connections after a difficult moment.',
  'High',
  'handshake-outline',
  '#FFF3E0',
  '#FB8C00',
  'Social Connection',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Morning Momentum',
  'Start the day with an easy, repeatable routine.',
  'Low',
  'weather-sunrise',
  '#E3F2FD',
  '#1E88E5',
  'Motivation',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Stressful Deadlines',
  'Manage pressure with planning and recovery cycles.',
  'High',
  'calendar-clock',
  '#E0F2F1',
  '#00796B',
  'Stress',
  10,
  'active',
  '[]'::jsonb,
  true
),
(
  'Low Energy Evenings',
  'Wind down without crashing your next day.',
  'Low',
  'moon-waning-crescent',
  '#F3E5F5',
  '#6A1B9A',
  'Energy',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Confidence Dip',
  'Rebuild self-belief through evidence-based wins.',
  'Moderate',
  'shield-star-outline',
  '#E8F5E9',
  '#2E7D32',
  'Motivation',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Lonely Weekend',
  'Plan low-effort ways to feel connected.',
  'Moderate',
  'account-heart-outline',
  '#FCE4EC',
  '#C2185B',
  'Social Connection',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Distracted Mornings',
  'Reduce distractions and set clear daily priorities.',
  'Moderate',
  'alarm-bell',
  '#E0F7FA',
  '#0097A7',
  'Focus',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'High-Stakes Presentation',
  'Prepare with calm routines and a clear structure.',
  'High',
  'presentation',
  '#E3F2FD',
  '#1565C0',
  'Social Connection',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Late-Night Overwork',
  'Create boundaries that protect recovery time.',
  'High',
  'clock-alert-outline',
  '#EDE7F6',
  '#4527A0',
  'Stress',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Low Morning Energy',
  'Build a simple morning activation routine.',
  'Moderate',
  'weather-sunset-up',
  '#FFF8E1',
  '#F9A825',
  'Energy',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Motivation After Setbacks',
  'Recover momentum with tiny, repeatable wins.',
  'High',
  'history',
  '#E8F5E9',
  '#2E7D32',
  'Motivation',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Social Burnout',
  'Balance connection with intentional downtime.',
  'Moderate',
  'account-off-outline',
  '#FCE4EC',
  '#C2185B',
  'Social Connection',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Noisy Environment',
  'Create focus zones and reduce ambient noise.',
  'Moderate',
  'volume-high',
  '#E0F7FA',
  '#00838F',
  'Focus',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Emotional Exhaustion',
  'Recover with rest, support, and gentle pacing.',
  'High',
  'heart-broken-outline',
  '#F3E5F5',
  '#6A1B9A',
  'Stress',
  10,
  'active',
  '[]'::jsonb,
  true
),
(
  'Unclear Priorities',
  'Clarify what matters most and cut noise.',
  'Moderate',
  'format-list-bulleted',
  '#E3F2FD',
  '#1E88E5',
  'Focus',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Motivation Slump',
  'Use micro-goals to rebuild drive.',
  'Low',
  'battery-low',
  '#FFF3E0',
  '#FB8C00',
  'Motivation',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Tense Team Dynamics',
  'Restore safety and clarity in group settings.',
  'High',
  'account-group-outline',
  '#EDE7F6',
  '#5E35B1',
  'Social Connection',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Interrupted Sleep',
  'Improve sleep quality with simple resets.',
  'Moderate',
  'sleep',
  '#E8F5E9',
  '#388E3C',
  'Energy',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Anxious Before Meetings',
  'Use quick calming tools before joining.',
  'Moderate',
  'account-voice',
  '#FCE4EC',
  '#AD1457',
  'Stress',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Energy Crash After Lunch',
  'Prevent crashes with a lighter routine.',
  'Low',
  'food-apple',
  '#FFF8E1',
  '#F9A825',
  'Energy',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Stuck on a Task',
  'Break tasks into the next smallest step.',
  'Moderate',
  'progress-clock',
  '#E0F7FA',
  '#0097A7',
  'Focus',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Motivation Without Direction',
  'Set clear targets and timelines.',
  'Moderate',
  'compass-outline',
  '#E8F5E9',
  '#2E7D32',
  'Motivation',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Social Confidence Dip',
  'Practice low-stakes social wins.',
  'Moderate',
  'account-star-outline',
  '#FCE4EC',
  '#C2185B',
  'Social Connection',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Stress Around Change',
  'Anchor yourself during transitions.',
  'High',
  'swap-horizontal',
  '#E3F2FD',
  '#1565C0',
  'Stress',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Low Energy Motivation Loop',
  'Use small habits to rebuild energy.',
  'Moderate',
  'repeat',
  '#FFF8E1',
  '#FBC02D',
  'Energy',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Overcommitted Schedule',
  'Reduce overload with a simple audit.',
  'High',
  'calendar-multiple',
  '#EDE7F6',
  '#4527A0',
  'Stress',
  10,
  'active',
  '[]'::jsonb,
  true
),
(
  'Low Focus in Meetings',
  'Use structured notes to stay present.',
  'Moderate',
  'account-eye-outline',
  '#E0F7FA',
  '#00838F',
  'Focus',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Motivation to Exercise',
  'Start with a 5-minute commitment.',
  'Low',
  'run',
  '#E8F5E9',
  '#2E7D32',
  'Motivation',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Team Connection Gap',
  'Bridge distance with small rituals.',
  'Moderate',
  'account-group',
  '#FCE4EC',
  '#C2185B',
  'Social Connection',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Stress From Uncertainty',
  'Focus on controllables and steady routines.',
  'High',
  'help-circle-outline',
  '#E3F2FD',
  '#1976D2',
  'Stress',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Afternoon Focus Fade',
  'Reset with movement and structured tasks.',
  'Moderate',
  'timer-outline',
  '#E0F7FA',
  '#00796B',
  'Focus',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Energy for Social Plans',
  'Plan lighter commitments that still connect.',
  'Low',
  'party-popper',
  '#FFF8E1',
  '#F9A825',
  'Energy',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Motivation to Learn',
  'Use short learning bursts to stay consistent.',
  'Moderate',
  'book-open-page-variant',
  '#E8F5E9',
  '#2E7D32',
  'Motivation',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Social Anxiety Before Events',
  'Plan safe exits and calming anchors.',
  'High',
  'account-alert-outline',
  '#FCE4EC',
  '#AD1457',
  'Social Connection',
  9,
  'active',
  '[]'::jsonb,
  true
),
(
  'Stress From Notifications',
  'Reduce alert fatigue with smart settings.',
  'Moderate',
  'bell-outline',
  '#EDE7F6',
  '#5E35B1',
  'Stress',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Focus During Study',
  'Create a distraction-free study block.',
  'Moderate',
  'book-open-variant',
  '#E0F7FA',
  '#00838F',
  'Focus',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Energy for Workouts',
  'Start small to rebuild movement habits.',
  'Low',
  'dumbbell',
  '#FFF8E1',
  '#F9A825',
  'Energy',
  7,
  'active',
  '[]'::jsonb,
  true
),
(
  'Motivation to Finish Projects',
  'Break work into a clear finish line.',
  'Moderate',
  'check-circle-outline',
  '#E8F5E9',
  '#2E7D32',
  'Motivation',
  8,
  'active',
  '[]'::jsonb,
  true
),
(
  'Social Confidence at Work',
  'Use simple scripts to feel more at ease.',
  'Moderate',
  'account-tie-outline',
  '#FCE4EC',
  '#C2185B',
  'Social Connection',
  8,
  'active',
  '[]'::jsonb,
  true
)
on conflict (title) do update
set
  description = excluded.description,
  level = excluded.level,
  icon = excluded.icon,
  bg = excluded.bg,
  color = excluded.color,
  category = excluded.category,
  priority = excluded.priority,
  status = excluded.status,
  tags = excluded.tags,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

insert into public.affirmations (
  content,
  tags,
  image,
  scheduled_date,
  status,
  is_active
)
values
(
  'I am steady, capable, and moving forward.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I choose progress over perfection today.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My focus improves with each small step.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I deserve rest and renewal.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I can handle challenges with calm.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I bring value to every room I enter.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am building momentum with consistency.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My work aligns with my goals.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I speak to myself with kindness.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am brave enough to start again.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I can do hard things with clarity.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am growing into my next level.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am worthy of good connections.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I protect my peace with clear boundaries.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I turn setbacks into lessons.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I honor my effort every day.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I create opportunity through action.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I listen with empathy and care.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am patient with my process.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I trust myself to figure it out.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My discipline builds my freedom.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I show up for the career I want.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I choose love in my self-talk.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I can ask for help when I need it.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am resilient and adaptable.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My consistency is my superpower.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am capable of meaningful work.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I cultivate relationships that uplift me.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I give myself grace today.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I move forward even when it is hard.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I stay committed to my goals.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My career grows with each decision.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I create safe space for connection.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am enough, exactly as I am.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I choose courage over comfort.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I finish what I start.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am proud of my progress.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I nurture the relationships that matter.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am gentle with myself in growth.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I have what it takes today.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I focus on what I can control.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My work is meaningful and impactful.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I show love through my actions.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I communicate with respect and care.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I release fear and choose progress.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I show up with purpose.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am open to new opportunities.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I give and receive love freely.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am building trust through honesty.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I choose patience and clarity today.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I embrace each day as a new beginning.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am becoming the best version of myself.',
  '["Growth"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My potential is limitless.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I attract positivity and abundance.',
  '["Gratitude"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am grateful for this moment.',
  '["Gratitude"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I release what no longer serves me.',
  '["Growth"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am worthy of success and happiness.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I trust the timing of my life.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am at peace with my past.',
  '["Growth"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My body is healthy and strong.',
  '["Health"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I choose joy in every moment.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am a magnet for miracles.',
  '["Gratitude"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I honor my own boundaries.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am confident in my decisions.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I attract meaningful connections.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My mind is calm and clear.',
  '["Health"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I welcome change with open arms.',
  '["Growth"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am creating the life I desire.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I celebrate my small victories.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I radiate warmth and kindness.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am exactly where I need to be.',
  '["Gratitude"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My challenges help me grow stronger.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I invest in my own growth daily.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I attract opportunities for success.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I speak my truth with confidence.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I nurture my body with healthy choices.',
  '["Health"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am surrounded by love and support.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I let go of comparison and embrace my journey.',
  '["Growth"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am a powerful creator of my reality.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My energy is contagious and uplifting.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I choose to see the good in every situation.',
  '["Gratitude"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am committed to my personal development.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I deserve all the good things coming my way.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I embrace uncertainty as an opportunity.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am building a life I love.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I treat myself with compassion and care.',
  '["Health"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am resilient and can overcome any obstacle.',
  '["Courage"]'::jsonb,
  'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I attract people who value and respect me.',
  '["Relationships"]'::jsonb,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am filled with gratitude for my blessings.',
  '["Gratitude"]'::jsonb,
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I take inspired action toward my goals.',
  '["Hard work"]'::jsonb,
  'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'My presence is a gift to those around me.',
  '["Love"]'::jsonb,
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I am in harmony with the universe.',
  '["Gratitude"]'::jsonb,
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I believe in my ability to succeed.',
  '["Career"]'::jsonb,
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
),
(
  'I prioritize my mental and physical health.',
  '["Health"]'::jsonb,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
  null,
  'active',
  true
)
on conflict (content) do update
set
  tags = excluded.tags,
  image = excluded.image,
  scheduled_date = excluded.scheduled_date,
  status = excluded.status,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

insert into public.assessment_questions (
  text,
  type,
  category,
  tags,
  weight,
  sort_order,
  is_active
)
values
(
  'I''ve been feeling relaxed',
  'scale',
  'General',
  '["Stress"]'::jsonb,
  1,
  1,
  true
),
(
  'I''ve been feeling useful',
  'scale',
  'General',
  '["Motivation"]'::jsonb,
  1,
  2,
  true
),
(
  'I''ve had energy to spare',
  'scale',
  'General',
  '["Energy"]'::jsonb,
  1,
  3,
  true
),
(
  'I''ve been feeling interested in other people',
  'scale',
  'General',
  '["Social Connection"]'::jsonb,
  1,
  4,
  true
),
(
  'I''ve been thinking clearly',
  'scale',
  'General',
  '["Focus"]'::jsonb,
  1,
  5,
  true
)
on conflict (text) do update
set
  type = excluded.type,
  category = excluded.category,
  tags = excluded.tags,
  weight = excluded.weight,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

insert into public.daily_affirmations (
  day_key,
  affirmation_id,
  slot_key,
  title
)
select
  seeded.day_key::date,
  affirmations.id,
  seeded.slot_key,
  seeded.title
from (
  values
(
  '2026-03-27',
  'I am steady, capable, and moving forward.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-03-28',
  'I choose progress over perfection today.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-03-29',
  'My focus improves with each small step.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-03-30',
  'I deserve rest and renewal.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-03-31',
  'I can handle challenges with calm.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-01',
  'I bring value to every room I enter.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-02',
  'I am building momentum with consistency.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-03',
  'My work aligns with my goals.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-04',
  'I speak to myself with kindness.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-05',
  'I am brave enough to start again.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-06',
  'I can do hard things with clarity.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-07',
  'I am growing into my next level.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-08',
  'I am worthy of good connections.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-09',
  'I protect my peace with clear boundaries.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-10',
  'I turn setbacks into lessons.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-11',
  'I honor my effort every day.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-12',
  'I create opportunity through action.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-13',
  'I listen with empathy and care.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-14',
  'I am patient with my process.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-15',
  'I trust myself to figure it out.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-16',
  'My discipline builds my freedom.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-17',
  'I show up for the career I want.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-18',
  'I choose love in my self-talk.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-19',
  'I can ask for help when I need it.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-20',
  'I am resilient and adaptable.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-21',
  'My consistency is my superpower.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-22',
  'I am capable of meaningful work.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-23',
  'I cultivate relationships that uplift me.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-24',
  'I give myself grace today.',
  'morning',
  'Daily Affirmation'
),
(
  '2026-04-25',
  'I move forward even when it is hard.',
  'morning',
  'Daily Affirmation'
)
) as seeded(day_key, affirmation_content, slot_key, title)
join public.affirmations as affirmations
  on affirmations.content = seeded.affirmation_content
on conflict (day_key, slot_key) do update
set
  affirmation_id = excluded.affirmation_id,
  title = excluded.title;
