// AUTO-GENERATED from backend/src/api/core.ts seed arrays

export const seedChallengeData = [
{
            title: 'Work-Life Balance',
            level: 'Moderate',
            icon: 'briefcase-outline',
            bg: '#E3F2FD',
            color: '#2196F3',
            category: 'Stress',
            priority: 10,
            status: 'active',
            description: 'Maintain a healthy boundary between work and personal life.',
        },
        {
            title: 'Social Anxiety',
            level: 'High',
            icon: 'account-group-outline',
            bg: '#F3E5F5',
            color: '#8E24AA',
            category: 'Social Connection',
            priority: 8,
            status: 'active',
            description: 'Strategies to manage discomfort in social settings.',
        },
        {
            title: 'Public Speaking',
            level: 'Moderate',
            icon: 'bullhorn-outline',
            bg: '#E1F5FE',
            color: '#0288D1',
            category: 'Social Connection',
            priority: 7,
            status: 'active',
            description: 'Build confidence in presenting to groups.',
        },
        {
            title: 'Procrastination',
            level: 'Moderate',
            icon: 'clock-outline',
            bg: '#FFF3E0',
            color: '#FF9800',
            category: 'Focus',
            priority: 9,
            status: 'active',
            description: 'Overcome the tendency to delay important tasks.',
        },
        {
            title: 'Sleep Hygiene',
            level: 'Low',
            icon: 'bed-outline',
            bg: '#E8F5E9',
            color: '#4CAF50',
            category: 'Energy',
            priority: 7,
            status: 'active',
            description: 'Improve your sleep quality with better routines.',
        }
        ,
        {
            title: 'Overthinking Spiral',
            level: 'High',
            icon: 'thought-bubble-outline',
            bg: '#F3E5F5',
            color: '#8E24AA',
            category: 'Stress',
            priority: 9,
            status: 'active',
            description: 'Reduce rumination with quick grounding techniques.',
        },
        {
            title: 'Afternoon Slump',
            level: 'Low',
            icon: 'weather-sunset-outline',
            bg: '#FFF8E1',
            color: '#F9A825',
            category: 'Energy',
            priority: 8,
            status: 'active',
            description: 'Boost energy with short breaks and hydration.',
        },
        {
            title: 'Low Motivation Week',
            level: 'Moderate',
            icon: 'flag-outline',
            bg: '#E8F5E9',
            color: '#43A047',
            category: 'Motivation',
            priority: 8,
            status: 'active',
            description: 'Rebuild momentum with tiny wins and clear goals.',
        },
        {
            title: 'Social Disconnection',
            level: 'High',
            icon: 'account-question-outline',
            bg: '#FCE4EC',
            color: '#D81B60',
            category: 'Social Connection',
            priority: 9,
            status: 'active',
            description: 'Reconnect with people through low-pressure outreach.',
        },
        {
            title: 'Focus Drift',
            level: 'Moderate',
            icon: 'target-variant',
            bg: '#E0F7FA',
            color: '#00838F',
            category: 'Focus',
            priority: 9,
            status: 'active',
            description: 'Improve concentration with timed sprints.',
        },
        {
            title: 'Decision Fatigue',
            level: 'Moderate',
            icon: 'playlist-check',
            bg: '#EDE7F6',
            color: '#5E35B1',
            category: 'Focus',
            priority: 7,
            status: 'active',
            description: 'Simplify choices to preserve mental energy.',
        },
        {
            title: 'Conflict Recovery',
            level: 'High',
            icon: 'handshake-outline',
            bg: '#FFF3E0',
            color: '#FB8C00',
            category: 'Social Connection',
            priority: 8,
            status: 'active',
            description: 'Repair connections after a difficult moment.',
        },
        {
            title: 'Morning Momentum',
            level: 'Low',
            icon: 'weather-sunrise',
            bg: '#E3F2FD',
            color: '#1E88E5',
            category: 'Motivation',
            priority: 7,
            status: 'active',
            description: 'Start the day with an easy, repeatable routine.',
        },
        {
            title: 'Stressful Deadlines',
            level: 'High',
            icon: 'calendar-clock',
            bg: '#E0F2F1',
            color: '#00796B',
            category: 'Stress',
            priority: 10,
            status: 'active',
            description: 'Manage pressure with planning and recovery cycles.',
        },
        {
            title: 'Low Energy Evenings',
            level: 'Low',
            icon: 'moon-waning-crescent',
            bg: '#F3E5F5',
            color: '#6A1B9A',
            category: 'Energy',
            priority: 7,
            status: 'active',
            description: 'Wind down without crashing your next day.',
        },
        {
            title: 'Confidence Dip',
            level: 'Moderate',
            icon: 'shield-star-outline',
            bg: '#E8F5E9',
            color: '#2E7D32',
            category: 'Motivation',
            priority: 8,
            status: 'active',
            description: 'Rebuild self-belief through evidence-based wins.',
        },
        {
            title: 'Lonely Weekend',
            level: 'Moderate',
            icon: 'account-heart-outline',
            bg: '#FCE4EC',
            color: '#C2185B',
            category: 'Social Connection',
            priority: 7,
            status: 'active',
            description: 'Plan low-effort ways to feel connected.',
        },
        {
            title: 'Distracted Mornings',
            level: 'Moderate',
            icon: 'alarm-bell',
            bg: '#E0F7FA',
            color: '#0097A7',
            category: 'Focus',
            priority: 8,
            status: 'active',
            description: 'Reduce distractions and set clear daily priorities.',
        },
        {
            title: 'High-Stakes Presentation',
            level: 'High',
            icon: 'presentation',
            bg: '#E3F2FD',
            color: '#1565C0',
            category: 'Social Connection',
            priority: 9,
            status: 'active',
            description: 'Prepare with calm routines and a clear structure.',
        },
        {
            title: 'Late-Night Overwork',
            level: 'High',
            icon: 'clock-alert-outline',
            bg: '#EDE7F6',
            color: '#4527A0',
            category: 'Stress',
            priority: 9,
            status: 'active',
            description: 'Create boundaries that protect recovery time.',
        },
        {
            title: 'Low Morning Energy',
            level: 'Moderate',
            icon: 'weather-sunset-up',
            bg: '#FFF8E1',
            color: '#F9A825',
            category: 'Energy',
            priority: 8,
            status: 'active',
            description: 'Build a simple morning activation routine.',
        },
        {
            title: 'Motivation After Setbacks',
            level: 'High',
            icon: 'history',
            bg: '#E8F5E9',
            color: '#2E7D32',
            category: 'Motivation',
            priority: 9,
            status: 'active',
            description: 'Recover momentum with tiny, repeatable wins.',
        },
        {
            title: 'Social Burnout',
            level: 'Moderate',
            icon: 'account-off-outline',
            bg: '#FCE4EC',
            color: '#C2185B',
            category: 'Social Connection',
            priority: 8,
            status: 'active',
            description: 'Balance connection with intentional downtime.',
        },
        {
            title: 'Noisy Environment',
            level: 'Moderate',
            icon: 'volume-high',
            bg: '#E0F7FA',
            color: '#00838F',
            category: 'Focus',
            priority: 7,
            status: 'active',
            description: 'Create focus zones and reduce ambient noise.',
        },
        {
            title: 'Emotional Exhaustion',
            level: 'High',
            icon: 'heart-broken-outline',
            bg: '#F3E5F5',
            color: '#6A1B9A',
            category: 'Stress',
            priority: 10,
            status: 'active',
            description: 'Recover with rest, support, and gentle pacing.',
        },
        {
            title: 'Unclear Priorities',
            level: 'Moderate',
            icon: 'format-list-bulleted',
            bg: '#E3F2FD',
            color: '#1E88E5',
            category: 'Focus',
            priority: 8,
            status: 'active',
            description: 'Clarify what matters most and cut noise.',
        },
        {
            title: 'Motivation Slump',
            level: 'Low',
            icon: 'battery-low',
            bg: '#FFF3E0',
            color: '#FB8C00',
            category: 'Motivation',
            priority: 7,
            status: 'active',
            description: 'Use micro-goals to rebuild drive.',
        },
        {
            title: 'Tense Team Dynamics',
            level: 'High',
            icon: 'account-group-outline',
            bg: '#EDE7F6',
            color: '#5E35B1',
            category: 'Social Connection',
            priority: 9,
            status: 'active',
            description: 'Restore safety and clarity in group settings.',
        },
        {
            title: 'Interrupted Sleep',
            level: 'Moderate',
            icon: 'sleep',
            bg: '#E8F5E9',
            color: '#388E3C',
            category: 'Energy',
            priority: 8,
            status: 'active',
            description: 'Improve sleep quality with simple resets.',
        },
        {
            title: 'Anxious Before Meetings',
            level: 'Moderate',
            icon: 'account-voice',
            bg: '#FCE4EC',
            color: '#AD1457',
            category: 'Stress',
            priority: 8,
            status: 'active',
            description: 'Use quick calming tools before joining.',
        },
        {
            title: 'Energy Crash After Lunch',
            level: 'Low',
            icon: 'food-apple',
            bg: '#FFF8E1',
            color: '#F9A825',
            category: 'Energy',
            priority: 7,
            status: 'active',
            description: 'Prevent crashes with a lighter routine.',
        },
        {
            title: 'Stuck on a Task',
            level: 'Moderate',
            icon: 'progress-clock',
            bg: '#E0F7FA',
            color: '#0097A7',
            category: 'Focus',
            priority: 8,
            status: 'active',
            description: 'Break tasks into the next smallest step.',
        },
        {
            title: 'Motivation Without Direction',
            level: 'Moderate',
            icon: 'compass-outline',
            bg: '#E8F5E9',
            color: '#2E7D32',
            category: 'Motivation',
            priority: 8,
            status: 'active',
            description: 'Set clear targets and timelines.',
        },
        {
            title: 'Social Confidence Dip',
            level: 'Moderate',
            icon: 'account-star-outline',
            bg: '#FCE4EC',
            color: '#C2185B',
            category: 'Social Connection',
            priority: 7,
            status: 'active',
            description: 'Practice low-stakes social wins.',
        },
        {
            title: 'Stress Around Change',
            level: 'High',
            icon: 'swap-horizontal',
            bg: '#E3F2FD',
            color: '#1565C0',
            category: 'Stress',
            priority: 9,
            status: 'active',
            description: 'Anchor yourself during transitions.',
        },
        {
            title: 'Low Energy Motivation Loop',
            level: 'Moderate',
            icon: 'repeat',
            bg: '#FFF8E1',
            color: '#FBC02D',
            category: 'Energy',
            priority: 8,
            status: 'active',
            description: 'Use small habits to rebuild energy.',
        },
        {
            title: 'Overcommitted Schedule',
            level: 'High',
            icon: 'calendar-multiple',
            bg: '#EDE7F6',
            color: '#4527A0',
            category: 'Stress',
            priority: 10,
            status: 'active',
            description: 'Reduce overload with a simple audit.',
        },
        {
            title: 'Low Focus in Meetings',
            level: 'Moderate',
            icon: 'account-eye-outline',
            bg: '#E0F7FA',
            color: '#00838F',
            category: 'Focus',
            priority: 7,
            status: 'active',
            description: 'Use structured notes to stay present.',
        },
        {
            title: 'Motivation to Exercise',
            level: 'Low',
            icon: 'run',
            bg: '#E8F5E9',
            color: '#2E7D32',
            category: 'Motivation',
            priority: 7,
            status: 'active',
            description: 'Start with a 5-minute commitment.',
        },
        {
            title: 'Team Connection Gap',
            level: 'Moderate',
            icon: 'account-group',
            bg: '#FCE4EC',
            color: '#C2185B',
            category: 'Social Connection',
            priority: 8,
            status: 'active',
            description: 'Bridge distance with small rituals.',
        },
        {
            title: 'Stress From Uncertainty',
            level: 'High',
            icon: 'help-circle-outline',
            bg: '#E3F2FD',
            color: '#1976D2',
            category: 'Stress',
            priority: 9,
            status: 'active',
            description: 'Focus on controllables and steady routines.',
        },
        {
            title: 'Afternoon Focus Fade',
            level: 'Moderate',
            icon: 'timer-outline',
            bg: '#E0F7FA',
            color: '#00796B',
            category: 'Focus',
            priority: 8,
            status: 'active',
            description: 'Reset with movement and structured tasks.',
        },
        {
            title: 'Energy for Social Plans',
            level: 'Low',
            icon: 'party-popper',
            bg: '#FFF8E1',
            color: '#F9A825',
            category: 'Energy',
            priority: 7,
            status: 'active',
            description: 'Plan lighter commitments that still connect.',
        },
        {
            title: 'Motivation to Learn',
            level: 'Moderate',
            icon: 'book-open-page-variant',
            bg: '#E8F5E9',
            color: '#2E7D32',
            category: 'Motivation',
            priority: 7,
            status: 'active',
            description: 'Use short learning bursts to stay consistent.',
        },
        {
            title: 'Social Anxiety Before Events',
            level: 'High',
            icon: 'account-alert-outline',
            bg: '#FCE4EC',
            color: '#AD1457',
            category: 'Social Connection',
            priority: 9,
            status: 'active',
            description: 'Plan safe exits and calming anchors.',
        },
        {
            title: 'Stress From Notifications',
            level: 'Moderate',
            icon: 'bell-outline',
            bg: '#EDE7F6',
            color: '#5E35B1',
            category: 'Stress',
            priority: 8,
            status: 'active',
            description: 'Reduce alert fatigue with smart settings.',
        },
        {
            title: 'Focus During Study',
            level: 'Moderate',
            icon: 'book-open-variant',
            bg: '#E0F7FA',
            color: '#00838F',
            category: 'Focus',
            priority: 8,
            status: 'active',
            description: 'Create a distraction-free study block.',
        },
        {
            title: 'Energy for Workouts',
            level: 'Low',
            icon: 'dumbbell',
            bg: '#FFF8E1',
            color: '#F9A825',
            category: 'Energy',
            priority: 7,
            status: 'active',
            description: 'Start small to rebuild movement habits.',
        },
        {
            title: 'Motivation to Finish Projects',
            level: 'Moderate',
            icon: 'check-circle-outline',
            bg: '#E8F5E9',
            color: '#2E7D32',
            category: 'Motivation',
            priority: 8,
            status: 'active',
            description: 'Break work into a clear finish line.',
        },
        {
            title: 'Social Confidence at Work',
            level: 'Moderate',
            icon: 'account-tie-outline',
            bg: '#FCE4EC',
            color: '#C2185B',
            category: 'Social Connection',
            priority: 8,
            status: 'active',
            description: 'Use simple scripts to feel more at ease.',
        }
];

export const seedResourceData = [
{
            title: 'The Art of Mindful Breathing',
            description: 'Learn how to use your breath to calm your nervous system instantly.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '5 min',
            color: '#E0F2F1',
            status: 'active',
            tags: ['Stress', 'Focus'],
        },
        {
            title: 'Building Better Morning Habits',
            description: 'Transform your day by implementing these simple morning rituals.',
            category: 'Self-development',
            tag: 'HABIT',
            time: '8 min',
            color: '#FFF3E0',
            status: 'active',
            tags: ['Energy', 'Motivation'],
        },
        {
            title: 'Managing Workplace Stress',
            description: 'Practical tips to keep your cool during high-pressure work days.',
            category: 'Self-development',
            tag: 'READ',
            time: '12 min',
            color: '#E3F2FD',
            status: 'active',
            tags: ['Stress'],
        },
        {
            title: 'Reset Your Nervous System',
            description: 'A short grounding routine to reduce overwhelm in 10 minutes.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '10 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Stress', 'Energy'],
        },
        {
            title: 'Focus Sprint: 25-Minute Deep Work',
            description: 'Use a simple sprint to improve concentration and finish tasks.',
            category: 'Self-development',
            tag: 'HABIT',
            time: '7 min',
            color: '#E0F7FA',
            status: 'active',
            tags: ['Focus', 'Motivation'],
        },
        {
            title: 'Sleep Wind-Down Checklist',
            description: 'Create an evening routine that makes sleep easier.',
            category: 'Self-development',
            tag: 'READ',
            time: '6 min',
            color: '#F3E5F5',
            status: 'active',
            tags: ['Energy', 'Stress'],
        },
        {
            title: 'Confidence in Small Talk',
            description: 'Simple prompts to ease social anxiety in new groups.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '9 min',
            color: '#FCE4EC',
            status: 'active',
            tags: ['Social Connection'],
        },
        {
            title: 'Reclaim Your Afternoon Energy',
            description: 'Avoid the 3pm slump with quick resets.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '5 min',
            color: '#FFF8E1',
            status: 'active',
            tags: ['Energy', 'Focus'],
        },
        {
            title: 'Values-Driven Goal Setting',
            description: 'Align weekly goals with what matters most to you.',
            category: 'Self-development',
            tag: 'READ',
            time: '11 min',
            color: '#E3F2FD',
            status: 'active',
            tags: ['Motivation', 'Focus'],
        },
        {
            title: 'Boundaries That Stick',
            description: 'Scripts for saying no without guilt.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '8 min',
            color: '#EDE7F6',
            status: 'active',
            tags: ['Stress', 'Social Connection'],
        },
        {
            title: 'Five-Minute Gratitude Reset',
            description: 'Shift your mood with a short gratitude exercise.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '5 min',
            color: '#FFF3E0',
            status: 'active',
            tags: ['Motivation', 'Energy'],
        },
        {
            title: 'A Better Way to Break Procrastination',
            description: 'Use tiny starts to reduce resistance.',
            category: 'Self-development',
            tag: 'READ',
            time: '7 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Focus', 'Motivation'],
        },
        {
            title: 'Calm Before Difficult Conversations',
            description: 'Preparation steps that reduce stress and improve outcomes.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '9 min',
            color: '#E0F2F1',
            status: 'active',
            tags: ['Stress', 'Social Connection'],
        },
        {
            title: 'Evening Stretch for Better Sleep',
            description: 'Light stretches to release tension.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '6 min',
            color: '#E3F2FD',
            status: 'active',
            tags: ['Energy', 'Stress'],
        },
        {
            title: 'Group Walk Challenge',
            description: 'Start a weekly circle walk to build consistency.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '20 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Energy', 'Social Connection'],
        },
        {
            title: 'Peer Accountability Sprint',
            description: 'Co-work for 30 minutes and share progress.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '30 min',
            color: '#E0F7FA',
            status: 'active',
            tags: ['Focus', 'Motivation'],
        },
        {
            title: 'Stress-Free Huddle',
            description: 'A guided group check-in to release stress.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '15 min',
            color: '#F3E5F5',
            status: 'active',
            tags: ['Stress', 'Social Connection'],
        },
        {
            title: 'Community Gratitude Circle',
            description: 'Share wins to boost motivation together.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '12 min',
            color: '#FFF8E1',
            status: 'active',
            tags: ['Motivation', 'Social Connection'],
        },
        {
            title: 'Evening Reflection Circle',
            description: 'Reflect on highs and lows with your circle.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '18 min',
            color: '#EDE7F6',
            status: 'active',
            tags: ['Focus', 'Social Connection'],
        },
        {
            title: 'Mindful Breathing Group',
            description: 'A shared 5-minute breathing break.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '5 min',
            color: '#E0F2F1',
            status: 'active',
            tags: ['Stress'],
        },
        {
            title: 'Goal-Setting Workshop',
            description: 'Set weekly goals and pair up for accountability.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '25 min',
            color: '#E3F2FD',
            status: 'active',
            tags: ['Motivation', 'Focus'],
        },
        {
            title: 'Social Recharge Challenge',
            description: 'Reach out to one person each day for a week.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '7 min',
            color: '#FCE4EC',
            status: 'active',
            tags: ['Social Connection'],
        },
        {
            title: 'Micro-Breaks for Focus',
            description: 'Take 2-minute breaks to reset attention.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '4 min',
            color: '#E0F7FA',
            status: 'active',
            tags: ['Focus'],
        },
        {
            title: 'Stress-Proof Morning',
            description: 'A morning flow that keeps your nervous system steady.',
            category: 'Self-development',
            tag: 'HABIT',
            time: '9 min',
            color: '#E3F2FD',
            status: 'active',
            tags: ['Stress', 'Energy'],
        },
        {
            title: 'Motivation Reset Ritual',
            description: 'A quick routine to restart momentum.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '6 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Motivation'],
        },
        {
            title: 'Focus Playlist Strategy',
            description: 'Use sound to create a deep work zone.',
            category: 'Self-development',
            tag: 'READ',
            time: '5 min',
            color: '#E0F2F1',
            status: 'active',
            tags: ['Focus'],
        },
        {
            title: 'Calm the Body Fast',
            description: 'Simple techniques to lower physical stress.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '5 min',
            color: '#F3E5F5',
            status: 'active',
            tags: ['Stress'],
        },
        {
            title: 'Connect With a Friend',
            description: 'Low-effort ideas to rebuild social energy.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '6 min',
            color: '#FCE4EC',
            status: 'active',
            tags: ['Social Connection'],
        },
        {
            title: 'Energy Through Nutrition',
            description: 'Simple fuel swaps for steadier energy.',
            category: 'Self-development',
            tag: 'READ',
            time: '7 min',
            color: '#FFF8E1',
            status: 'active',
            tags: ['Energy'],
        },
        {
            title: 'Confidence for Hard Tasks',
            description: 'A short checklist to start tough work.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '6 min',
            color: '#EDE7F6',
            status: 'active',
            tags: ['Motivation', 'Focus'],
        },
        {
            title: 'Recover After Conflict',
            description: 'Steps to calm down and reconnect.',
            category: 'Self-development',
            tag: 'READ',
            time: '8 min',
            color: '#FCE4EC',
            status: 'active',
            tags: ['Stress', 'Social Connection'],
        },
        {
            title: 'Weekly Planning Lite',
            description: 'A 10-minute plan to reduce overwhelm.',
            category: 'Self-development',
            tag: 'HABIT',
            time: '10 min',
            color: '#E3F2FD',
            status: 'active',
            tags: ['Focus', 'Stress'],
        },
        {
            title: 'Energy Check-In',
            description: 'A simple self-scan to pace your day.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '4 min',
            color: '#FFF8E1',
            status: 'active',
            tags: ['Energy'],
        },
        {
            title: 'Social Warm-Up',
            description: 'Easy prompts to start conversations.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '5 min',
            color: '#FCE4EC',
            status: 'active',
            tags: ['Social Connection'],
        },
        {
            title: 'Stress Relief Walk',
            description: 'A 10-minute walk to decompress.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '10 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Stress', 'Energy'],
        },
        {
            title: 'Motivation Through Meaning',
            description: 'Reconnect with your core values.',
            category: 'Self-development',
            tag: 'READ',
            time: '9 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Motivation'],
        },
        {
            title: 'Focus-Friendly Workspace',
            description: 'Arrange your space for deep work.',
            category: 'Self-development',
            tag: 'READ',
            time: '6 min',
            color: '#E0F7FA',
            status: 'active',
            tags: ['Focus'],
        },
        {
            title: 'Evening Digital Detox',
            description: 'Lower stimulation before sleep.',
            category: 'Self-development',
            tag: 'HABIT',
            time: '7 min',
            color: '#F3E5F5',
            status: 'active',
            tags: ['Stress', 'Energy'],
        },
        {
            title: 'Gratitude Text Challenge',
            description: 'Send one thankful message each day.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '5 min',
            color: '#FFF8E1',
            status: 'active',
            tags: ['Motivation', 'Social Connection'],
        },
        {
            title: 'Co-Working Focus Session',
            description: 'Join a 45-minute group focus block.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '45 min',
            color: '#E0F7FA',
            status: 'active',
            tags: ['Focus', 'Motivation'],
        },
        {
            title: 'Group Stretch Break',
            description: 'A short stretch routine with your circle.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '8 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Energy', 'Stress'],
        },
        {
            title: 'Evening Wins Share',
            description: 'Share a small win with the group.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '6 min',
            color: '#EDE7F6',
            status: 'active',
            tags: ['Motivation', 'Social Connection'],
        },
        {
            title: 'Morning Intention Circle',
            description: 'Set a daily intention with your team.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '6 min',
            color: '#E3F2FD',
            status: 'active',
            tags: ['Focus', 'Motivation'],
        },
        {
            title: 'Stress Check-In Huddle',
            description: 'Rate stress together and share coping ideas.',
            category: 'Group activities',
            tag: 'GROUP',
            time: '10 min',
            color: '#F3E5F5',
            status: 'active',
            tags: ['Stress', 'Social Connection'],
        },
        {
            title: 'Energy Boost Playlist',
            description: 'A short music break to lift energy.',
            category: 'Self-development',
            tag: 'PRACTICE',
            time: '4 min',
            color: '#FFF8E1',
            status: 'active',
            tags: ['Energy'],
        },
        {
            title: 'Focus Anchor Technique',
            description: 'Return attention quickly when distracted.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '5 min',
            color: '#E0F7FA',
            status: 'active',
            tags: ['Focus'],
        },
        {
            title: 'Motivation From Progress',
            description: 'Track tiny wins to stay consistent.',
            category: 'Self-development',
            tag: 'HABIT',
            time: '6 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Motivation'],
        },
        {
            title: 'Social Confidence Reframe',
            description: 'Reframe anxious thoughts before events.',
            category: 'Self-development',
            tag: 'LEARN',
            time: '7 min',
            color: '#FCE4EC',
            status: 'active',
            tags: ['Social Connection', 'Stress'],
        },
        {
            title: 'Stress Boundary Scripts',
            description: 'Phrases to protect your time.',
            category: 'Self-development',
            tag: 'READ',
            time: '6 min',
            color: '#EDE7F6',
            status: 'active',
            tags: ['Stress'],
        },
        {
            title: 'Energy-Friendly Lunch',
            description: 'Small meal tweaks that reduce crashes.',
            category: 'Self-development',
            tag: 'READ',
            time: '5 min',
            color: '#FFF8E1',
            status: 'active',
            tags: ['Energy'],
        },
        {
            title: 'Focus With Time Blocks',
            description: 'Plan deep work windows in your day.',
            category: 'Self-development',
            tag: 'HABIT',
            time: '8 min',
            color: '#E0F7FA',
            status: 'active',
            tags: ['Focus'],
        },
        {
            title: 'Motivation Through Rewards',
            description: 'Use small rewards to sustain effort.',
            category: 'Self-development',
            tag: 'READ',
            time: '6 min',
            color: '#E8F5E9',
            status: 'active',
            tags: ['Motivation'],
        },
        {
            title: 'Social Connection Micro-Goals',
            description: 'Set tiny goals to stay connected.',
            category: 'Self-development',
            tag: 'HABIT',
            time: '5 min',
            color: '#FCE4EC',
            status: 'active',
            tags: ['Social Connection'],
        }
];

export const seedAffirmationImages = [
'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80',
        'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1080&q=80'
];

export const seedAffirmationData = [
{ content: 'I am steady, capable, and moving forward.', tags: ['Courage'], status: 'active' },
        { content: 'I choose progress over perfection today.', tags: ['Hard work'], status: 'active' },
        { content: 'My focus improves with each small step.', tags: ['Career'], status: 'active' },
        { content: 'I deserve rest and renewal.', tags: ['Love'], status: 'active' },
        { content: 'I can handle challenges with calm.', tags: ['Courage'], status: 'active' },
        { content: 'I bring value to every room I enter.', tags: ['Relationships'], status: 'active' },
        { content: 'I am building momentum with consistency.', tags: ['Hard work'], status: 'active' },
        { content: 'My work aligns with my goals.', tags: ['Career'], status: 'active' },
        { content: 'I speak to myself with kindness.', tags: ['Love'], status: 'active' },
        { content: 'I am brave enough to start again.', tags: ['Courage'], status: 'active' },
        { content: 'I can do hard things with clarity.', tags: ['Hard work'], status: 'active' },
        { content: 'I am growing into my next level.', tags: ['Career'], status: 'active' },
        { content: 'I am worthy of good connections.', tags: ['Relationships'], status: 'active' },
        { content: 'I protect my peace with clear boundaries.', tags: ['Love'], status: 'active' },
        { content: 'I turn setbacks into lessons.', tags: ['Courage'], status: 'active' },
        { content: 'I honor my effort every day.', tags: ['Hard work'], status: 'active' },
        { content: 'I create opportunity through action.', tags: ['Career'], status: 'active' },
        { content: 'I listen with empathy and care.', tags: ['Relationships'], status: 'active' },
        { content: 'I am patient with my process.', tags: ['Love'], status: 'active' },
        { content: 'I trust myself to figure it out.', tags: ['Courage'], status: 'active' },
        { content: 'My discipline builds my freedom.', tags: ['Hard work'], status: 'active' },
        { content: 'I show up for the career I want.', tags: ['Career'], status: 'active' },
        { content: 'I choose love in my self-talk.', tags: ['Love'], status: 'active' },
        { content: 'I can ask for help when I need it.', tags: ['Relationships'], status: 'active' },
        { content: 'I am resilient and adaptable.', tags: ['Courage'], status: 'active' },
        { content: 'My consistency is my superpower.', tags: ['Hard work'], status: 'active' },
        { content: 'I am capable of meaningful work.', tags: ['Career'], status: 'active' },
        { content: 'I cultivate relationships that uplift me.', tags: ['Relationships'], status: 'active' },
        { content: 'I give myself grace today.', tags: ['Love'], status: 'active' },
        { content: 'I move forward even when it is hard.', tags: ['Courage'], status: 'active' },
        { content: 'I stay committed to my goals.', tags: ['Hard work'], status: 'active' },
        { content: 'My career grows with each decision.', tags: ['Career'], status: 'active' },
        { content: 'I create safe space for connection.', tags: ['Relationships'], status: 'active' },
        { content: 'I am enough, exactly as I am.', tags: ['Love'], status: 'active' },
        { content: 'I choose courage over comfort.', tags: ['Courage'], status: 'active' },
        { content: 'I finish what I start.', tags: ['Hard work'], status: 'active' },
        { content: 'I am proud of my progress.', tags: ['Career'], status: 'active' },
        { content: 'I nurture the relationships that matter.', tags: ['Relationships'], status: 'active' },
        { content: 'I am gentle with myself in growth.', tags: ['Love'], status: 'active' },
        { content: 'I have what it takes today.', tags: ['Courage'], status: 'active' },
        { content: 'I focus on what I can control.', tags: ['Hard work'], status: 'active' },
        { content: 'My work is meaningful and impactful.', tags: ['Career'], status: 'active' },
        { content: 'I show love through my actions.', tags: ['Love'], status: 'active' },
        { content: 'I communicate with respect and care.', tags: ['Relationships'], status: 'active' },
        { content: 'I release fear and choose progress.', tags: ['Courage'], status: 'active' },
        { content: 'I show up with purpose.', tags: ['Hard work'], status: 'active' },
        { content: 'I am open to new opportunities.', tags: ['Career'], status: 'active' },
        { content: 'I give and receive love freely.', tags: ['Love'], status: 'active' },
        { content: 'I am building trust through honesty.', tags: ['Relationships'], status: 'active' },
        { content: 'I choose patience and clarity today.', tags: ['Courage'], status: 'active' }
];
