import fs from 'node:fs';
import path from 'node:path';

const root = '/Users/sulaymaanabubakr/Desktop/Empylo';
const seedDataPath = path.join(root, 'backend/src/seedData.ts');
const questionSeedPath = path.join(root, 'backend/scripts/seed_questions.ts');
const outputPath = path.join(root, 'supabase backend/supabase/seed.sql');

const sqlString = (value) => {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
};

const sqlJson = (value) => `${sqlString(JSON.stringify(value ?? null))}::jsonb`;

const normalizeResourceAccess = (item) => {
  const category = String(item?.category || '').trim().toLowerCase();
  const kind = category.includes('group') ? 'group_activity' : 'self_development';
  return {
    kind,
    plans: ['pro'],
    shareRequiresPremium: false
  };
};

const loadLegacyContent = () => {
  const source = fs.readFileSync(seedDataPath, 'utf8');
  const executable = `${source.replace(/export const /g, 'const ')}\nreturn { seedChallengeData, seedResourceData, seedAffirmationImages, seedAffirmationData };`;
  return Function(executable)();
};

const loadQuestions = () => {
  const source = fs.readFileSync(questionSeedPath, 'utf8');
  const match = source.match(/const questions = (\[[\s\S]*?\n\]);/);
  if (!match) {
    throw new Error('Unable to find questions array in seed_questions.ts');
  }
  return Function(`return ${match[1]};`)();
};

const {
  seedChallengeData,
  seedResourceData,
  seedAffirmationImages,
  seedAffirmationData
} = loadLegacyContent();
const questions = loadQuestions();

const today = new Date().toISOString().slice(0, 10);

const resourceRows = seedResourceData.map((item) => `(
  ${sqlString(item.title)},
  ${sqlString(item.description || '')},
  ${sqlString(item.content || '')},
  ${sqlString(item.contentFormat || 'html')},
  ${sqlString(item.image || '')},
  ${sqlString(item.category || '')},
  ${sqlString(item.tag || '')},
  ${sqlString(item.time || '')},
  ${sqlString(item.color || '')},
  ${sqlString(item.status || 'active')},
  ${sqlJson(item.tags || [])},
  ${sqlJson(item.access || normalizeResourceAccess(item))}
)`).join(',\n');

const challengeRows = seedChallengeData.map((item) => `(
  ${sqlString(item.title)},
  ${sqlString(item.description || '')},
  ${sqlString(item.level || '')},
  ${sqlString(item.icon || '')},
  ${sqlString(item.bg || '')},
  ${sqlString(item.color || '')},
  ${sqlString(item.category || '')},
  ${Number.isFinite(item.priority) ? item.priority : 0},
  ${sqlString(item.status || 'active')},
  ${sqlJson(item.tags || [])},
  ${item.isActive === false ? 'false' : 'true'}
)`).join(',\n');

const affirmationRows = seedAffirmationData.map((item, index) => `(
  ${sqlString(item.content)},
  ${sqlJson(item.tags || [])},
  ${sqlString(seedAffirmationImages[index % seedAffirmationImages.length] || '')},
  ${sqlString(item.scheduledDate || null)},
  ${sqlString(item.status || 'active')},
  ${item.isActive === false ? 'false' : 'true'}
)`).join(',\n');

const questionRows = questions.map((item) => `(
  ${sqlString(item.text)},
  ${sqlString(item.type || 'scale')},
  ${sqlString(item.category || 'General')},
  ${sqlJson(item.tags || [])},
  ${Number.isFinite(item.weight) ? item.weight : 1},
  ${Number.isFinite(item.order) ? item.order : 0},
  ${item.isActive === false ? 'false' : 'true'}
)`).join(',\n');

const affirmationSlots = [
  { key: 'morning', title: 'Morning Affirmation', offset: 0 },
  { key: 'afternoon', title: 'Afternoon Affirmation', offset: 1 },
  { key: 'evening', title: 'Evening Affirmation', offset: 2 },
];

const dailyRows = Array.from({ length: Math.min(seedAffirmationData.length, 30) }, (_, index) => {
  const date = new Date(`${today}T00:00:00.000Z`);
  date.setUTCDate(date.getUTCDate() + index);
  return affirmationSlots.map((slot) => {
    const affirmation = seedAffirmationData[(index * affirmationSlots.length + slot.offset) % seedAffirmationData.length];
    return `(
  ${sqlString(date.toISOString().slice(0, 10))},
  ${sqlString(affirmation.content)},
  ${sqlString(slot.key)},
  ${sqlString(slot.title)}
)`;
  }).join(',\n');
}).join(',\n');

const sql = `-- Generated by scripts/generate_content_seed.mjs
-- Source: backend/src/seedData.ts and backend/scripts/seed_questions.ts

insert into public.resources (
  title,
  description,
  content,
  content_format,
  image,
  category,
  tag,
  time,
  color,
  status,
  tags,
  access
)
values
${resourceRows}
on conflict (title) do update
set
  description = excluded.description,
  content = excluded.content,
  content_format = excluded.content_format,
  image = excluded.image,
  category = excluded.category,
  tag = excluded.tag,
  time = excluded.time,
  color = excluded.color,
  status = excluded.status,
  tags = excluded.tags,
  access = excluded.access,
  updated_at = timezone('utc', now());

insert into public.challenges (
  title,
  description,
  level,
  icon,
  bg,
  color,
  category,
  priority,
  status,
  tags,
  is_active
)
values
${challengeRows}
on conflict (title) do update
set
  description = excluded.description,
  level = excluded.level,
  icon = excluded.icon,
  bg = excluded.bg,
  color = excluded.color,
  category = excluded.category,
  priority = excluded.priority,
  status = excluded.status,
  tags = excluded.tags,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

insert into public.affirmations (
  content,
  tags,
  image,
  scheduled_date,
  status,
  is_active
)
values
${affirmationRows}
on conflict (content) do update
set
  tags = excluded.tags,
  image = excluded.image,
  scheduled_date = excluded.scheduled_date,
  status = excluded.status,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

insert into public.assessment_questions (
  text,
  type,
  category,
  tags,
  weight,
  sort_order,
  is_active
)
values
${questionRows}
on conflict (text) do update
set
  type = excluded.type,
  category = excluded.category,
  tags = excluded.tags,
  weight = excluded.weight,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

insert into public.daily_affirmations (
  day_key,
  affirmation_id,
  slot_key,
  title
)
select
  seeded.day_key::date,
  affirmations.id,
  seeded.slot_key,
  seeded.title
from (
  values
${dailyRows}
) as seeded(day_key, affirmation_content, slot_key, title)
join public.affirmations as affirmations
  on affirmations.content = seeded.affirmation_content
on conflict (day_key, slot_key) do update
set
  affirmation_id = excluded.affirmation_id,
  title = excluded.title;
`;

fs.writeFileSync(outputPath, sql);
console.log(`Generated ${outputPath}`);
console.log(JSON.stringify({
  resources: seedResourceData.length,
  challenges: seedChallengeData.length,
  affirmations: seedAffirmationData.length,
  assessmentQuestions: questions.length,
  dailyAffirmations: Math.min(seedAffirmationData.length, 30)
}, null, 2));
