export declare const onUserCreate: import("firebase-functions/v1").CloudFunction<import("firebase-admin/auth").UserRecord>;
export declare const onMessageCreate: import("firebase-functions/v1").CloudFunction<import("firebase-functions/v1/firestore").QueryDocumentSnapshot>;
export declare const generateUploadSignature: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const createCircle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const joinCircle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const updateCircle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const leaveCircle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const deleteCircle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const manageMember: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const handleJoinRequest: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const resolveCircleReport: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const submitReport: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const startHuddle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const joinHuddle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const declineHuddle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const endHuddle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const ringHuddleParticipants: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const ringPendingHuddles: import("firebase-functions/scheduler").ScheduleFunction;
export declare const updateHuddleState: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const updateHuddleConnection: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const cleanupStaleHuddles: import("firebase-functions/scheduler").ScheduleFunction;
export declare const scheduleHuddle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const deleteScheduledHuddle: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const toggleScheduledHuddleReminder: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const processScheduledHuddles: import("firebase-functions/scheduler").ScheduleFunction;
export declare const createDirectChat: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const blockUser: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const unblockUser: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getPublicProfile: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const sendMessage: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const deleteChat: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const submitAssessment: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getUserStats: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getKeyChallenges: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const seedChallenges: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const seedResources: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const seedAssessmentQuestions: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const fixAssessmentQuestionsText: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const seedAffirmations: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const backfillAffirmationImages: import("firebase-functions/v1").HttpsFunction;
export declare const seedAll: import("firebase-functions/v1").HttpsFunction;
export declare const getSeedStatus: import("firebase-functions/v1").HttpsFunction;
export declare const updateSubscription: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getExploreContent: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getRecommendedContent: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getAffirmations: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const submitContactForm: import("firebase-functions/v1").HttpsFunction;
export declare const sendAffirmationsMorning: import("firebase-functions/scheduler").ScheduleFunction;
export declare const sendAffirmationsAfternoon: import("firebase-functions/scheduler").ScheduleFunction;
export declare const sendAffirmationsEvening: import("firebase-functions/scheduler").ScheduleFunction;
export declare const deleteUserAccount: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const requestOtp: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const verifyOtp: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const registerWithOtp: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const resetPasswordWithOtp: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const changePasswordWithOtp: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const completeEmailVerificationWithOtp: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const changeEmailWithOtp: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const recordLoginDevice: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getDashboardStats: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getAllUsers: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getPendingContent: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getAllContent: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const updateContentStatus: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const updateContentItem: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const toggleUserStatus: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const deleteItem: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getAdminAffirmations: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const createAffirmation: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const deleteAffirmation: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getTransactions: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getReports: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const resolveReport: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getSupportTickets: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const updateTicketStatus: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const backfillUserCircles: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const bulkUpdateContent: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const getAdminAuditLogs: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const createEmployee: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
//# sourceMappingURL=index.d.ts.map